server:
  port: 8090
spring:
  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, yupi
      routes:
        # 定义了一个名为"api_route"的路由规则,该规则将匹配以"/api/"开头的路径,例如"/api/user",
        # 并将这些请求转发到"http://localhost:8123"这个目标地址
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

# 配置应用的名称，使用协议，注册中心类型（这里使用nacos）和地址
dubbo:
  application:
    # 设置应用的名称
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: 22223
#    port: -1 （随机端口）
  registry:
    # 配置注册中心为nacos，地址为nacos://localhost:8848
    id: nacos-registry
    address: nacos://localhost:8848