spring:
  application:
    name: API-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api_db
    username: root
    password: 589274
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#  elk
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: 123456

  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: none # none | redis 关闭/开启redis存储session

  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)